### ISSUE TITLE
custom component suddenly stopped working

### ISSUE THREAD

**Issue by mjoshd** [djtimca/haomnilogic#51]
Firstly, thank you for this awesome custom component!

The custom component had been installed and worked great for a month or so.

As of 2 days ago it no longer works.
![image](https://github.com/djtimca/haomnilogic/assets/35782597/e84f8a26-945c-4b0b-9922-c3bacb45ff86)

Still able to log in on https://www.haywardomnilogic.com without issue (this was done from an alternate location; not home at the moment).

Was able to run telemetry gathering steps without issue (this was done from an alternate location; not home at the moment).

Please let me know if you need any extra info or anything done on my side for testing. 

Copied from Home Assistant 'About' page:
```
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest
```

Copied from Home Assistant logs:
```
2023-05-24 06:41:51.613 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration omnilogic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-24 06:42:08.820 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Omnilogic for omnilogic
File "/config/custom_components/omnilogic/__init__.py", line 44, in async_setup_entry
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 166, in connect
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 148, in authenticate
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 143, in _get_new_token
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 129, in _get_token
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 100, in call_api
```

Copied from Home Assistant logs with debugging enabled on the custom component from the Integrations page:
```
2023-05-24 07:39:24.045 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration omnilogic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-24 07:39:35.228 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Omnilogic for omnilogic
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/omnilogic/__init__.py", line 44, in async_setup_entry
await api.connect()
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 166, in connect
await self.authenticate()
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 148, in authenticate
response = await self._get_new_token()
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 143, in _get_new_token
return await self._get_token()
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 129, in _get_token
response = await self.call_api("Login", params)
File "/usr/local/lib/python3.10/site-packages/omnilogic/__init__.py", line 100, in call_api
responseXML = ElementTree.fromstring(response)
File "/usr/local/lib/python3.10/xml/etree/ElementTree.py", line 1343, in XML
return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

output_116_3b978abdd8_telemetry.json
```json
[{'systemId': 'REDACTED', 'statusVersion': '5', 'airTemp': '67', 'status': '1', 'state': '1', 'configUpdatedTime': '2023-05-23T12:57:25.365Z', 'datetime': '2023-05-24T07:09:31.7144957', 'Relays': [], 'BOWS': [{'systemId': '1', 'flow': '255', 'waterTemp': '84', 'Name': 'Pool', 'Supports-Spillover': 'no', 'Filter': {'systemId': '2', 'valvePosition': '1', 'filterSpeed': '50', 'filterState': '1', 'lastSpeed': '50', 'Name': 'Filter Pump', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP', 'Max-Pump-Speed': '100', 'Min-Pump-Speed': '18', 'Max-Pump-RPM': '3450', 'Min-Pump-RPM': '600', 'Priming-Enabled': 'yes', 'Alarms': []}, 'VirtualHeater': {'systemId': '5', 'Current-Set-Point': '87', 'enable': 'yes'}, 'Heater': {'systemId': '6', 'heaterState': '1', 'enable': 'yes', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Operation': {'VirtualHeater': {'System-Id': '6', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_1', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_8HRS', 'Shared-Equipment-System-ID': '-1', 'Current-Set-Point': '87', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '5'}}, 'Name': 'Heater', 'Alarms': []}, 'CSAD': {'systemId': '0', 'ph': '', 'orp': '', 'status': '0', 'mode': '0', 'Alarms': []}, 'Group': {'systemId': '15', 'groupState': '0'}, 'Lights': [{'systemId': '10', 'lightState': '0', 'currentShow': '0', 'speed': '4', 'brightness': '4', 'Name': 'UCL', 'Type': 'COLOR_LOGIC_UCL', 'V2': 'yes', 'Alarms': []}], 'Relays': [{'systemId': '21', 'relayState': '0', 'Name': 'Jet-Slide', 'Type': 'RLY_VALVE_ACTUATOR', 'Function': 'RLY_LAMINARS', 'Alarms': []}, {'systemId': '23', 'relayState': '0', 'Name': 'WaterSlide', 'Type': 'RLY_VALVE_ACTUATOR', 'Function': 'RLY_WATER_SLIDE', 'Alarms': []}], 'Pumps': [], 'Heaters': [{'systemId': '6', 'heaterState': '1', 'enable': 'yes', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Operation': {'VirtualHeater': {'System-Id': '6', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_1', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_8HRS', 'Shared-Equipment-System-ID': '-1', 'Current-Set-Point': '87', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '5'}}, 'Name': 'Heater', 'Alarms': []}]}], 'BackyardName': 'REDACTED', 'Msp-Vsp-Speed-Format': 'Percent', 'Msp-Time-Format': '12 Hour Format', 'Units': 'Standard', 'Msp-Chlor-Display': 'Salt', 'Msp-Language': 'English', 'Unit-of-Measurement': 'Standard', 'Alarms': [], 'Unit-of-Temperature': 'UNITS_FAHRENHEIT'}]
```

output_116_6f71ff94d0_mspconfig.xml
```xml
<Response><MSPConfig><System><Msp-Vsp-Speed-Format>Percent</Msp-Vsp-Speed-Format><Msp-Time-Format>12 Hour Format</Msp-Time-Format><Units>Standard</Units><Msp-Chlor-Display>Salt</Msp-Chlor-Display><Msp-Language>English</Msp-Language><UI-Display-Mode>standard</UI-Display-Mode><UI-MoodColor-Enabled>Yes</UI-MoodColor-Enabled><UI-Heater-SimpleMode>Yes</UI-Heater-SimpleMode><UI-Filter-SimpleMode>Yes</UI-Filter-SimpleMode><UI-Lights-SimpleMode>Yes</UI-Lights-SimpleMode></System><Backyard>
        MSP Configuration
        <System-Id>0</System-Id><Name>Backyard</Name><Service-Mode-Timeout>0</Service-Mode-Timeout><Sensor><System-Id>4</System-Id><Name>AirSensor</Name><Type>SENSOR_AIR_TEMP</Type><Units>UNITS_FAHRENHEIT</Units></Sensor><Body-of-water>
            01
            <System-Id>1</System-Id><Name>Pool</Name><Type>BOW_POOL</Type><Shared-Type>BOW_NO_EQUIPMENT_SHARED</Shared-Type><Shared-Priority>SHARED_EQUIPMENT_LOW_PRIORITY</Shared-Priority><Shared-Equipment-System-ID>0</Shared-Equipment-System-ID><Supports-Spillover>no</Supports-Spillover><Size-In-Gallons>27000</Size-In-Gallons><Filter><System-Id>2</System-Id><Name>Filter Pump</Name><Shared-Type>BOW_NO_EQUIPMENT_SHARED</Shared-Type><Filter-Type>FMT_VARIABLE_SPEED_PUMP</Filter-Type><Max-Pump-Speed>100</Max-Pump-Speed><Min-Pump-Speed>18</Min-Pump-Speed><Max-Pump-RPM>3450</Max-Pump-RPM><Min-Pump-RPM>600</Min-Pump-RPM><Priming-Enabled>yes</Priming-Enabled><Vsp-Low-Pump-Speed>18</Vsp-Low-Pump-Speed><Vsp-Medium-Pump-Speed>50</Vsp-Medium-Pump-Speed><Vsp-High-Pump-Speed>100</Vsp-High-Pump-Speed><Vsp-Custom-Pump-Speed>100</Vsp-Custom-Pump-Speed><Freeze-Protect-Override-Interval>7200</Freeze-Protect-Override-Interval></Filter><Sensor><System-Id>3</System-Id><Name>WaterSensor</Name><Type>SENSOR_WATER_TEMP</Type><Units>UNITS_FAHRENHEIT</Units></Sensor><Heater><System-Id>5</System-Id><Shared-Type>BOW_NO_EQUIPMENT_SHARED</Shared-Type><Enabled>yes</Enabled><Current-Set-Point>87</Current-Set-Point><Max-Water-Temp>104</Max-Water-Temp><Min-Settable-Water-Temp>65</Min-Settable-Water-Temp><Max-Settable-Water-Temp>104</Max-Settable-Water-Temp><Operation>
                    PEO_HEATER_EQUIPMENT
                    <Heater-Equipment><System-Id>6</System-Id><Name>Heater</Name><Type>PET_HEATER</Type><Heater-Type>HTR_GAS</Heater-Type><Enabled>yes</Enabled><Priority>HTR_PRIORITY_1</Priority><Run-For-Priority>HTR_MAINTAINS_PRIORITY_FOR_8HRS</Run-For-Priority><Shared-Equipment-System-ID>-1</Shared-Equipment-System-ID></Heater-Equipment></Operation></Heater><ColorLogic-Light><System-Id>10</System-Id><Name>UCL</Name><Type>COLOR_LOGIC_UCL</Type><V2-Active>yes</V2-Active></ColorLogic-Light><Relay><System-Id>21</System-Id><Name>Jet-Slide</Name><Type>RLY_VALVE_ACTUATOR</Type><Function>RLY_LAMINARS</Function><Valve-Default-Speed>78</Valve-Default-Speed></Relay><Relay><System-Id>23</System-Id><Name>WaterSlide</Name><Type>RLY_VALVE_ACTUATOR</Type><Function>RLY_WATER_SLIDE</Function><Valve-Default-Speed>78</Valve-Default-Speed></Relay></Body-of-water></Backyard><Schedules><sche><bow-system-id>1</bow-system-id><equipment-id>2</equipment-id><schedule-system-id>8</schedule-system-id><event>164</event><data>36</data><enabled>0</enabled><start-minute>59</start-minute><start-hour>11</start-hour><end-minute>0</end-minute><end-hour>19</end-hour><days-active>127</days-active><recurring>1</recurring></sche><sche><bow-system-id>1</bow-system-id><equipment-id>2</equipment-id><schedule-system-id>11</schedule-system-id><event>164</event><data>65</data><enabled>0</enabled><start-minute>0</start-minute><start-hour>8</start-hour><end-minute>59</end-minute><end-hour>11</end-hour><days-active>127</days-active><recurring>1</recurring></sche><sche><bow-system-id>1</bow-system-id><equipment-id>2</equipment-id><schedule-system-id>12</schedule-system-id><event>164</event><data>18</data><enabled>0</enabled><start-minute>0</start-minute><start-hour>19</start-hour><end-minute>59</end-minute><end-hour>7</end-hour><days-active>127</days-active><recurring>1</recurring></sche><sche><bow-system-id>1</bow-system-id><equipment-id>5</equipment-id><schedule-system-id>13</schedule-system-id><event>164</event><data>82</data><enabled>0</enabled><start-minute>0</start-minute><start-hour>8</start-hour><end-minute>59</end-minute><end-hour>19</end-hour><days-active>127</days-active><recurring>1</recurring></sche><sche><bow-system-id>1</bow-system-id><equipment-id>5</equipment-id><schedule-system-id>14</schedule-system-id><event>164</event><data>74</data><enabled>0</enabled><start-minute>0</start-minute><start-hour>20</start-hour><end-minute>59</end-minute><end-hour>6</end-hour><days-active>127</days-active><recurring>1</recurring></sche><sche><bow-system-id>1</bow-system-id><equipment-id>21</equipment-id><schedule-system-id>22</schedule-system-id><event>164</event><data>1</data><enabled>0</enabled><start-minute>0</start-minute><start-hour>0</start-hour><end-minute>1</end-minute><end-hour>0</end-hour><days-active>64</days-active><recurring>1</recurring></sche></Schedules><Favorites><Favorite><System-Id>16</System-Id><Index-Id>1</Index-Id><EquipmentID-Or-ThemeID>15</EquipmentID-Or-ThemeID><Sequence>0</Sequence><Data>268435455</Data><SimpleModeEnabled>1</SimpleModeEnabled></Favorite></Favorites><Groups><Group><System-Id>15</System-Id><Name>CFC</Name><Icon-Id>0</Icon-Id><Request><Name>TurnOnOffForGroup</Name><Parameters><Parameter name="PoolID" dataType="int">1</Parameter><Parameter name="EquipmentID" dataType="int">2</Parameter><Parameter name="Data" dataType="int">100</Parameter><Parameter name="LightState" dataType="int">0</Parameter></Parameters></Request><Request><Name>SetHeaterScheduleCmd</Name><Parameters><Parameter name="PoolID" dataType="int">1</Parameter><Parameter name="HeaterID" dataType="int">5</Parameter><Parameter name="Temp" dataType="int">92</Parameter><Parameter name="IsCountDownTimer" dataType="bool">0</Parameter><Parameter name="StartTimeHours" dataType="int">0</Parameter><Parameter name="StartTimeMinutes" dataType="int">0</Parameter><Parameter name="EndTimeHours" dataType="int">0</Parameter><Parameter name="EndTimeMinutes" dataType="int">0</Parameter><Parameter name="DaysActive" dataType="int">0</Parameter><Parameter name="Recurring" dataType="bool">0</Parameter></Parameters></Request><Request><Name>SetUITemporaryHeaterPriorityCmd</Name><Parameters><Parameter name="PoolID" dataType="int">1</Parameter><Parameter name="HeaterID1" dataType="int">6</Parameter><Parameter name="HeaterID2" dataType="int">-1</Parameter><Parameter name="HeaterID3" dataType="int">-1</Parameter><Parameter name="HeaterID4" dataType="int">-1</Parameter><Parameter name="HeaterID5" dataType="int">-1</Parameter></Parameters></Request><Request><Name>SetUITemporaryHeaterMaintainPriorityCmd</Name><Parameters><Parameter name="PoolID" dataType="int">1</Parameter><Parameter name="HeaterID" dataType="int">5</Parameter><Parameter name="Priority1MaintainFor" dataType="byte">8</Parameter><Parameter name="Priority2MaintainFor" dataType="byte">255</Parameter><Parameter name="Priority3MaintainFor" dataType="byte">255</Parameter><Parameter name="Priority4MaintainFor" dataType="byte">255</Parameter><Parameter name="Priority5MaintainFor" dataType="byte">255</Parameter></Parameters></Request><Request><Name>SetUITemporaryHeaterEnable</Name><Parameters><Parameter name="PoolID" dataType="int">1</Parameter><Parameter name="HeaterID" dataType="int">5</Parameter><Parameter name="Enabled" dataType="int">1</Parameter></Parameters></Request><Request><Name>SetUITemporaryHeaterEnable</Name><Parameters><Parameter name="PoolID" dataType="int">1</Parameter><Parameter name="HeaterID" dataType="int">6</Parameter><Parameter name="Enabled" dataType="int">1</Parameter></Parameters></Request><Request><Name>TurnOnOffForGroup</Name><Parameters><Parameter name="PoolID" dataType="int">1</Parameter><Parameter name="EquipmentID" dataType="int">10</Parameter><Parameter name="Data" dataType="int">263436</Parameter><Parameter name="LightState" dataType="int">1</Parameter></Parameters></Request></Group></Groups></MSPConfig><MSPAPI version="0.4" latestversion="0.4"><Device-APIs><API System-Id="15" OpType="ON_OFF" ref="RunGroupCmd" ThemeID="15" IsOn="API::STATUS::Group::groupState" /><API System-Id="2" OpType="ON_OFF" ref="SetUIEquipmentCmd" EquipmentID="2" IsOn="API::STATUS::Filter::filterSpeed" /><API System-Id="5" OpType="ON_OFF" ref="SetHeaterEnable" HeaterID="5" /><API System-Id="5" OpType="SETPOINT" ref="SetUIHeaterCmd" HeaterID="5" Temp="API::STATUS::VirtualHeater::Current-Set-Point" /><API System-Id="21" OpType="ON_OFF" ref="SetUIEquipmentCmd" EquipmentID="21" IsOn="API::STATUS::Relay::relayState" /><API System-Id="23" OpType="ON_OFF" ref="SetUIEquipmentCmd" EquipmentID="23" IsOn="API::STATUS::Relay::relayState" /><API System-Id="10" OpType="ON_OFF" ref="SetUIEquipmentCmd" EquipmentID="10" IsOn="API::STATUS::ColorLogic-Light::lightState" /><API System-Id="10" OpType="ON_SETPOINT" ref="SetStandAloneLightShowV2" LightID="10" Show="API::STATUS::ColorLogic-Light::currentShow" Speed="API::STATUS::ColorLogic-Light::speed" Brightness="API::STATUS::ColorLogic-Light::brightness" /><API System-Id="0" OpType="CSAD_MODE" ref="UISetCSADMode" CSADID="0" Mode="API::STATUS::CSAD::mode" /><API System-Id="0" OpType="CSAD_CALIBRATION" ref="UISetCSADTargetValue" CSADID="0" Mode="API::STATUS::CSAD::ph" /></Device-APIs><Favorite-APIs><API Favorite-Id="15" ref="RunGroupCmd" OpType="ON_OFF" ThemeID="15" IsOn="API::STATUS::Group::groupState" /><API Favorite-Id="2" ref="SetUIEquipmentCmd" OpType="ON_OFF" EquipmentID="2" IsOn="API::STATUS::Filter::filterState" /><API Favorite-Id="5" ref="API::GOTOFEATURE" /><API Favorite-Id="1" ref="SetHeaterEnable" HeaterID="5" /><API Favorite-Id="21" ref="SetUIEquipmentCmd" OpType="ON_OFF" EquipmentID="21" /><API Favorite-Id="23" ref="SetUIEquipmentCmd" OpType="ON_OFF" EquipmentID="23" /><API Favorite-Id="10" ref="SetStandAloneLightShowV2" OpType="ON_SETPOINT" LightID="10" Show="API::CONFIG::Favorite::Data" Speed="API::CONFIG::Favorite::Data2" Brightness="API::CONFIG::Favorite::Data3" /><API Favorite-Id="0" ref="API::GOTOFEATURE" /></Favorite-APIs><Schedule-APIs><API System-Id="15" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="15" Data="1" ActionID="317" /><API System-Id="15" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="1" ActionID="317" /><API System-Id="15" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id" /><API System-Id="2" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="2" Data="API::STATUS::Filter::filterSpeed" ActionID="164" /><API System-Id="2" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="API::STATUS::Filter::filterSpeed" ActionID="164" /><API System-Id="2" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id" /><API System-Id="5" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="5" Data="API::STATUS::VirtualHeater::Current-Set-Point" ActionID="315" /><API System-Id="5" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="API::STATUS::VirtualHeater::Current-Set-Point" ActionID="315" /><API System-Id="5" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id" /><API System-Id="21" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="21" Data="1" ActionID="164" /><API System-Id="21" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="1" ActionID="164" /><API System-Id="21" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id" /><API System-Id="23" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="23" Data="1" ActionID="164" /><API System-Id="23" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="1" ActionID="164" /><API System-Id="23" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id" /><API System-Id="10" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleAltCmd" EquipmentID="10" Show="API::STATUS::ColorLogic-Light::currentShow" Speed="API::STATUS::ColorLogic-Light::speed" Brightness="API::STATUS::ColorLogic-Light::brightness" Data4="0" ActionID="308" /><API System-Id="10" OpType="EDIT_SCHEDULE" ref="EditUIScheduleAltCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Show="API::STATUS::ColorLogic-Light::currentShow" Speed="API::STATUS::ColorLogic-Light::speed" Brightness="API::STATUS::ColorLogic-Light::brightness" Data4="0" ActionID="308" /><API System-Id="10" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id" /></Schedule-APIs></MSPAPI></Response>
```

output_116_97c83ba006_telemetry.xml
```xml
<STATUS version="1.0"><Backyard systemId="109660" statusVersion="5" airTemp="67" status="1" state="1" configUpdatedTime="2023-05-23T12:57:25.365Z" datetime="2023-05-24T07:09:31.7144957" /><BodyOfWater systemId="1" flow="255" waterTemp="84" /><Filter systemId="2" valvePosition="1" filterSpeed="50" filterState="1" lastSpeed="50" /><VirtualHeater systemId="5" Current-Set-Point="87" enable="yes" /><Heater systemId="6" heaterState="1" enable="yes" /><Relay systemId="21" relayState="0" /><Relay systemId="23" relayState="0" /><ColorLogic-Light systemId="10" lightState="0" currentShow="0" speed="4" brightness="4" /><CSAD systemId="0" ph="" orp="" status="0" mode="0" /><Group systemId="15" groupState="0" /></STATUS>
```

**Comment by bweb1122** [comment]
I had the same issue the other day but by mid-day it started working without issue. Seems like it's something the Omni's side.

https://github.com/djtimca/haomnilogic/issues/50
