### ISSUE TITLE
OmniLogic log error Invalid Config

### ISSUE THREAD

**Issue by rob7419** [djtimca/haomnilogic#57]
Upgraded to HA 2024.2.0 and on reboot the Omnilogic gave a notification that it failed to load. 

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 6:16:03 PM (1 occurrences)
Last logged: 6:16:03 PM

Setup failed for custom integration 'omnilogic': Unable to import component: No module named 'importlib_metadata'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/omnilogic/__init__.py", line 12, in <module>
    from .common import OmniLogicUpdateCoordinator
  File "/config/custom_components/omnilogic/common.py", line 6, in <module>
    from importlib_metadata import NullFinder
ModuleNotFoundError: No module named 'importlib_metadata'

**Comment by twillux** [comment]
As a temporary workaround I commented out common.py line 6: from importlib_metadata import NullFinder

This allows the integration to successfully start with no observed issues so far. I’m not versed enough in HA python integrations to understand the full implications, but wanted to share this as a stop-gap while this issue is reviewed.
