### ISSUE TITLE
1.0.3 reverted out the relay fixes

### ISSUE THREAD

**Issue by MHillyer** [djtimca/haomnilogic#6]
Upgraded for the icons, lost all the relays.

**Comment by djtimca** [comment]
Of course! Any errors in the logs this time?

**Comment by MHillyer** [comment]
Unexpected error fetching Omnilogic data: syntax error: line 1, column 0
2:47:46 PM – (ERROR) Omnilogic (custom integration)
Error reporting state - 5: Requested entity was not found.
2:43:48 PM – (WARNING) Home Assistant Cloud
Error while setting up omnilogic platform for switch
2:43:47 PM – (ERROR) Switch (custom integration) - message first occurred at 2:42:11 PM and shows up 2 times

File "/config/custom_components/omnilogic/switch.py", line 41, in async_setup_entry
entity = entity_class(
File "/config/custom_components/omnilogic/switch.py", line 158, in __init__
super().__init__(
File "/config/custom_components/omnilogic/switch.py", line 80, in __init__
icon = SWITCH_ICONS[switch_type]
KeyError: 'PMP_SINGLE_SPEED'
2022-06-03 14:42:38 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xF8E5:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0xf8e5:1:0x0006]: Message send failure'), DeliveryError('[0xf8e5:1:0x0006]: Message send failure'), DeliveryError('[0xf8e5:1:0x0006]: Message send failure'), DeliveryError('[0xf8e5:1:0x0006]: Message send failure')]
2022-06-03 14:42:41 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xF8E5:1:0x0b04]: async_initialize: all attempts have failed: [DeliveryError('[0xf8e5:1:0x0b04]: Message send failure'), DeliveryError('[0xf8e5:1:0x0b04]: Message send failure'), DeliveryError('[0xf8e5:1:0x0b04]: Message send failure'), DeliveryError('[0xf8e5:1:0x0b04]: Message send failure')]
2022-06-03 14:43:47 ERROR (MainThread) [homeassistant.components.switch] Error while setting up omnilogic platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/omnilogic/switch.py", line 41, in async_setup_entry
entity = entity_class(
File "/config/custom_components/omnilogic/switch.py", line 158, in __init__
super().__init__(
File "/config/custom_components/omnilogic/switch.py", line 80, in __init__
icon = SWITCH_ICONS[switch_type]
KeyError: 'PMP_SINGLE_SPEED'
2022-06-03 14:43:48 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2022-06-03 14:47:46 ERROR (MainThread) [custom_components.omnilogic.common] Unexpected error fetching Omnilogic data: syntax error: line 1, column 0
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/omnilogic/common.py", line 47, in _async_update_data
data = await self.api.get_telemetry_data()
File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 1008, in get_telemetry_data
site_telem = self.telemetry_to_json(telem, config_item, self.alarms_to_json(this_alarm))
File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 719, in telemetry_to_json
telemetryXML = ElementTree.fromstring(telemetry)
File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1349, in XML
parser.feed(text)
